[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "taxonomake"
version = "0.0.1"
authors = [
  { name="Tim Lamberton" },
]
description = "Configurable generator for taxonomic profiling benchmarks"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"

[project.scripts]
taxonomake = "taxonomake.taxonomake:main"

[project.urls]
Homepage = "https://github.com/wwood/singlem-benchmarking"