[workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[environments]
art = ["art"]
gtdbtk-r207 = ["gtdbtk-r207"]
datasets = ["datasets"]
parallel = ["parallel"]

[feature.art.dependencies]
python = ">=3.10,<3.14"
art = "*"
pandas = "*"
extern = "*"
polars = "*"
pyarrow = "*"
pigz = "*"

[feature.gtdbtk-r207.dependencies]
gtdbtk = "==2.1.0"
numpy = "<=1.20"

[feature.datasets.dependencies]
ncbi-datasets-cli = "*"

[feature.parallel.dependencies]
parallel = "*"