from taxonomake.modules.common import (
    config_sample_reads1,
    config_sample_reads2,
    config_truth
)

if "classify" in config:
    module classify:
        snakefile: "classify/classify.smk"
        config: config

    use rule * from classify

if "coverages" in config:
    module coverages:
        snakefile: "coverages/coverages.smk"
        config: config
    
    use rule * from coverages

if "readsim" in config:
    module simulate:
        snakefile: "simulate/simulate.smk"
        config: config
    
    use rule * from simulate

rule all:
    input:
        config_sample_reads1(config),
        config_sample_reads2(config),
        config_truth(config)
    localrule: True